spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/game?serverTimezone=CET
    username: dergax
    password: Test
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

